// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hardware_pid_engine_hardware_pid_engine,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.923000,HLS_SYN_LAT=34,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4485,HLS_SYN_LUT=3673,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module hardware_pid_engine (
        ap_clk,
        ap_rst_n,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 61'd1;
parameter    ap_ST_fsm_state2 = 61'd2;
parameter    ap_ST_fsm_state3 = 61'd4;
parameter    ap_ST_fsm_state4 = 61'd8;
parameter    ap_ST_fsm_state5 = 61'd16;
parameter    ap_ST_fsm_state6 = 61'd32;
parameter    ap_ST_fsm_state7 = 61'd64;
parameter    ap_ST_fsm_state8 = 61'd128;
parameter    ap_ST_fsm_state9 = 61'd256;
parameter    ap_ST_fsm_state10 = 61'd512;
parameter    ap_ST_fsm_state11 = 61'd1024;
parameter    ap_ST_fsm_state12 = 61'd2048;
parameter    ap_ST_fsm_state13 = 61'd4096;
parameter    ap_ST_fsm_state14 = 61'd8192;
parameter    ap_ST_fsm_state15 = 61'd16384;
parameter    ap_ST_fsm_state16 = 61'd32768;
parameter    ap_ST_fsm_state17 = 61'd65536;
parameter    ap_ST_fsm_state18 = 61'd131072;
parameter    ap_ST_fsm_state19 = 61'd262144;
parameter    ap_ST_fsm_state20 = 61'd524288;
parameter    ap_ST_fsm_state21 = 61'd1048576;
parameter    ap_ST_fsm_state22 = 61'd2097152;
parameter    ap_ST_fsm_state23 = 61'd4194304;
parameter    ap_ST_fsm_state24 = 61'd8388608;
parameter    ap_ST_fsm_state25 = 61'd16777216;
parameter    ap_ST_fsm_state26 = 61'd33554432;
parameter    ap_ST_fsm_state27 = 61'd67108864;
parameter    ap_ST_fsm_state28 = 61'd134217728;
parameter    ap_ST_fsm_state29 = 61'd268435456;
parameter    ap_ST_fsm_state30 = 61'd536870912;
parameter    ap_ST_fsm_state31 = 61'd1073741824;
parameter    ap_ST_fsm_state32 = 61'd2147483648;
parameter    ap_ST_fsm_state33 = 61'd4294967296;
parameter    ap_ST_fsm_state34 = 61'd8589934592;
parameter    ap_ST_fsm_state35 = 61'd17179869184;
parameter    ap_ST_fsm_state36 = 61'd34359738368;
parameter    ap_ST_fsm_state37 = 61'd68719476736;
parameter    ap_ST_fsm_state38 = 61'd137438953472;
parameter    ap_ST_fsm_state39 = 61'd274877906944;
parameter    ap_ST_fsm_state40 = 61'd549755813888;
parameter    ap_ST_fsm_state41 = 61'd1099511627776;
parameter    ap_ST_fsm_state42 = 61'd2199023255552;
parameter    ap_ST_fsm_state43 = 61'd4398046511104;
parameter    ap_ST_fsm_state44 = 61'd8796093022208;
parameter    ap_ST_fsm_state45 = 61'd17592186044416;
parameter    ap_ST_fsm_state46 = 61'd35184372088832;
parameter    ap_ST_fsm_state47 = 61'd70368744177664;
parameter    ap_ST_fsm_state48 = 61'd140737488355328;
parameter    ap_ST_fsm_state49 = 61'd281474976710656;
parameter    ap_ST_fsm_state50 = 61'd562949953421312;
parameter    ap_ST_fsm_state51 = 61'd1125899906842624;
parameter    ap_ST_fsm_state52 = 61'd2251799813685248;
parameter    ap_ST_fsm_state53 = 61'd4503599627370496;
parameter    ap_ST_fsm_state54 = 61'd9007199254740992;
parameter    ap_ST_fsm_state55 = 61'd18014398509481984;
parameter    ap_ST_fsm_state56 = 61'd36028797018963968;
parameter    ap_ST_fsm_state57 = 61'd72057594037927936;
parameter    ap_ST_fsm_state58 = 61'd144115188075855872;
parameter    ap_ST_fsm_state59 = 61'd288230376151711744;
parameter    ap_ST_fsm_state60 = 61'd576460752303423488;
parameter    ap_ST_fsm_state61 = 61'd1152921504606846976;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [60:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] set_roll;
wire   [31:0] set_pitch;
wire   [31:0] set_yaw;
wire   [31:0] gyro_x;
wire   [31:0] gyro_y;
wire   [31:0] gyro_z;
wire   [31:0] kp;
wire   [31:0] ki;
wire   [31:0] kd;
wire   [31:0] dt;
wire   [31:0] throttle;
wire   [31:0] out_roll;
reg    out_roll_ap_vld;
wire   [31:0] out_pitch;
reg    out_pitch_ap_vld;
wire   [31:0] out_yaw;
reg    out_yaw_ap_vld;
reg   [31:0] roll_st_integ;
reg   [31:0] roll_st_last_err;
reg   [31:0] pitch_st_integ;
reg   [31:0] pitch_st_last_err;
reg   [31:0] yaw_st_integ;
reg   [31:0] yaw_st_last_err;
reg   [31:0] reg_276;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
reg   [31:0] reg_280;
reg   [31:0] reg_284;
reg  signed [31:0] dt_read_reg_681;
reg   [31:0] kd_read_reg_687;
reg   [31:0] ki_read_reg_692;
reg  signed [31:0] kp_read_reg_697;
wire  signed [31:0] err_fu_288_p2;
reg  signed [31:0] err_reg_702;
wire  signed [31:0] err_1_fu_294_p2;
reg  signed [31:0] err_1_reg_709;
wire  signed [31:0] err_2_fu_300_p2;
reg  signed [31:0] err_2_reg_716;
wire  signed [47:0] sext_ln7_fu_306_p1;
wire    ap_CS_fsm_state2;
wire  signed [47:0] sext_ln7_1_fu_312_p1;
wire  signed [47:0] sext_ln7_2_fu_317_p1;
wire   [31:0] diff_fu_327_p2;
reg   [31:0] diff_reg_743;
wire  signed [47:0] sext_ln7_5_fu_337_p1;
wire   [31:0] diff_1_fu_346_p2;
reg   [31:0] diff_1_reg_754;
wire  signed [47:0] sext_ln7_7_fu_356_p1;
reg   [31:0] P_reg_765;
reg   [31:0] P_1_reg_770;
reg   [31:0] a_assign_1_reg_775;
reg   [31:0] P_2_reg_780;
reg   [31:0] a_assign_2_reg_785;
wire  signed [47:0] sext_ln7_3_fu_391_p1;
wire    ap_CS_fsm_state4;
wire  signed [47:0] sext_ln7_4_fu_396_p1;
reg  signed [47:0] sext_ln7_4_reg_795;
wire   [0:0] icmp_ln23_fu_402_p2;
reg   [0:0] icmp_ln23_reg_805;
wire  signed [47:0] sext_ln7_6_fu_407_p1;
wire  signed [47:0] sext_ln7_8_fu_411_p1;
wire   [31:0] diff_2_fu_419_p2;
reg   [31:0] diff_2_reg_819;
wire   [31:0] add_ln20_fu_428_p2;
reg   [31:0] add_ln20_reg_824;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln20_1_fu_444_p2;
reg   [31:0] add_ln20_1_reg_829;
wire   [31:0] add_ln20_2_fu_460_p2;
reg   [31:0] add_ln20_2_reg_834;
wire  signed [47:0] sext_ln7_9_fu_472_p1;
wire  signed [47:0] sext_ln7_10_fu_478_p1;
wire  signed [47:0] sext_ln7_11_fu_482_p1;
wire  signed [47:0] sext_ln7_12_fu_486_p1;
wire    ap_CS_fsm_state8;
wire   [31:0] trunc_ln23_fu_529_p1;
wire    ap_CS_fsm_state59;
wire   [31:0] trunc_ln23_1_fu_533_p1;
wire   [31:0] trunc_ln23_2_fu_537_p1;
wire   [31:0] out_9_fu_551_p2;
reg   [31:0] out_9_reg_891;
wire    ap_CS_fsm_state60;
wire   [0:0] icmp_ln28_fu_556_p2;
reg   [0:0] icmp_ln28_reg_896;
wire   [31:0] out_12_fu_567_p2;
reg   [31:0] out_12_reg_901;
wire   [0:0] icmp_ln28_1_fu_572_p2;
reg   [0:0] icmp_ln28_1_reg_906;
wire   [31:0] out_fu_583_p2;
reg   [31:0] out_reg_911;
wire   [0:0] icmp_ln28_2_fu_588_p2;
reg   [0:0] icmp_ln28_2_reg_916;
reg   [31:0] cond_i2773_reg_189;
reg   [31:0] cond_i6971_reg_200;
reg   [31:0] D_reg_211;
wire    ap_CS_fsm_state61;
reg  signed [31:0] grp_fu_222_p0;
reg  signed [31:0] grp_fu_222_p1;
reg  signed [31:0] grp_fu_226_p0;
reg  signed [31:0] grp_fu_226_p1;
reg  signed [31:0] grp_fu_230_p0;
reg  signed [31:0] grp_fu_230_p1;
wire  signed [31:0] grp_fu_234_p0;
wire  signed [31:0] grp_fu_238_p1;
wire  signed [31:0] grp_fu_242_p0;
wire  signed [31:0] grp_fu_242_p1;
wire   [47:0] grp_fu_222_p2;
wire   [47:0] grp_fu_226_p2;
wire   [47:0] grp_fu_230_p2;
wire   [47:0] grp_fu_234_p2;
wire   [47:0] grp_fu_238_p2;
wire   [47:0] grp_fu_242_p2;
wire   [47:0] grp_fu_498_p0;
wire  signed [31:0] grp_fu_498_p1;
wire   [47:0] grp_fu_511_p0;
wire  signed [31:0] grp_fu_511_p1;
wire   [47:0] grp_fu_524_p0;
wire  signed [31:0] grp_fu_524_p1;
wire   [31:0] grp_fu_498_p2;
wire   [31:0] grp_fu_511_p2;
wire   [31:0] grp_fu_524_p2;
wire   [31:0] add_ln26_fu_546_p2;
wire   [31:0] add_ln26_2_fu_562_p2;
wire   [31:0] add_ln26_4_fu_578_p2;
wire   [31:0] out_10_fu_594_p3;
wire   [0:0] icmp_ln29_fu_604_p2;
wire   [17:0] trunc_ln29_fu_600_p1;
wire   [17:0] out_11_fu_610_p3;
wire   [31:0] out_13_fu_623_p3;
wire   [0:0] icmp_ln29_1_fu_633_p2;
wire   [17:0] trunc_ln29_1_fu_629_p1;
wire   [17:0] out_14_fu_639_p3;
wire   [31:0] out_7_fu_652_p3;
wire   [0:0] icmp_ln29_2_fu_662_p2;
wire   [17:0] trunc_ln26_fu_658_p1;
wire   [17:0] out_8_fu_668_p3;
reg    grp_fu_498_ap_start;
wire    grp_fu_498_ap_done;
reg    grp_fu_511_ap_start;
wire    grp_fu_511_ap_done;
reg    grp_fu_524_ap_start;
wire    grp_fu_524_ap_done;
reg   [60:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 61'd1;
#0 roll_st_integ = 32'd0;
#0 roll_st_last_err = 32'd0;
#0 pitch_st_integ = 32'd0;
#0 pitch_st_last_err = 32'd0;
#0 yaw_st_integ = 32'd0;
#0 yaw_st_last_err = 32'd0;
end

hardware_pid_engine_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .set_roll(set_roll),
    .set_pitch(set_pitch),
    .set_yaw(set_yaw),
    .gyro_x(gyro_x),
    .gyro_y(gyro_y),
    .gyro_z(gyro_z),
    .kp(kp),
    .ki(ki),
    .kd(kd),
    .dt(dt),
    .throttle(throttle),
    .out_roll(out_roll),
    .out_roll_ap_vld(out_roll_ap_vld),
    .out_pitch(out_pitch),
    .out_pitch_ap_vld(out_pitch_ap_vld),
    .out_yaw(out_yaw),
    .out_yaw_ap_vld(out_yaw_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

hardware_pid_engine_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_222_p0),
    .din1(grp_fu_222_p1),
    .ce(1'b1),
    .dout(grp_fu_222_p2)
);

hardware_pid_engine_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_226_p0),
    .din1(grp_fu_226_p1),
    .ce(1'b1),
    .dout(grp_fu_226_p2)
);

hardware_pid_engine_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_230_p0),
    .din1(grp_fu_230_p1),
    .ce(1'b1),
    .dout(grp_fu_230_p2)
);

hardware_pid_engine_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_234_p0),
    .din1(err_1_reg_709),
    .ce(1'b1),
    .dout(grp_fu_234_p2)
);

hardware_pid_engine_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(kp_read_reg_697),
    .din1(grp_fu_238_p1),
    .ce(1'b1),
    .dout(grp_fu_238_p2)
);

hardware_pid_engine_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_242_p0),
    .din1(grp_fu_242_p1),
    .ce(1'b1),
    .dout(grp_fu_242_p2)
);

hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 52 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_48ns_32s_32_52_seq_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_498_ap_start),
    .done(grp_fu_498_ap_done),
    .din0(grp_fu_498_p0),
    .din1(grp_fu_498_p1),
    .ce(1'b1),
    .dout(grp_fu_498_p2)
);

hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 52 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_48ns_32s_32_52_seq_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_511_ap_start),
    .done(grp_fu_511_ap_done),
    .din0(grp_fu_511_p0),
    .din1(grp_fu_511_p1),
    .ce(1'b1),
    .dout(grp_fu_511_p2)
);

hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 52 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_48ns_32s_32_52_seq_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_524_ap_start),
    .done(grp_fu_524_ap_done),
    .din0(grp_fu_524_p0),
    .din1(grp_fu_524_p1),
    .ce(1'b1),
    .dout(grp_fu_524_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln23_reg_805 == 1'd1))) begin
        D_reg_211 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state59) & (icmp_ln23_reg_805 == 1'd0))) begin
        D_reg_211 <= trunc_ln23_2_fu_537_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln23_reg_805 == 1'd1))) begin
        cond_i2773_reg_189 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state59) & (icmp_ln23_reg_805 == 1'd0))) begin
        cond_i2773_reg_189 <= trunc_ln23_1_fu_533_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln23_reg_805 == 1'd1))) begin
        cond_i6971_reg_200 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state59) & (icmp_ln23_reg_805 == 1'd0))) begin
        cond_i6971_reg_200 <= trunc_ln23_fu_529_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        P_1_reg_770 <= {{grp_fu_230_p2[47:16]}};
        P_2_reg_780 <= {{grp_fu_238_p2[47:16]}};
        P_reg_765 <= {{grp_fu_222_p2[47:16]}};
        a_assign_1_reg_775 <= {{grp_fu_234_p2[47:16]}};
        a_assign_2_reg_785 <= {{grp_fu_242_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln20_1_reg_829 <= add_ln20_1_fu_444_p2;
        add_ln20_2_reg_834 <= add_ln20_2_fu_460_p2;
        add_ln20_reg_824 <= add_ln20_fu_428_p2;
        pitch_st_integ <= add_ln20_1_fu_444_p2;
        roll_st_integ <= add_ln20_fu_428_p2;
        yaw_st_integ <= add_ln20_2_fu_460_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        diff_1_reg_754 <= diff_1_fu_346_p2;
        diff_reg_743 <= diff_fu_327_p2;
        pitch_st_last_err <= err_1_reg_709;
        roll_st_last_err <= err_reg_702;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        diff_2_reg_819 <= diff_2_fu_419_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        dt_read_reg_681 <= dt;
        err_1_reg_709 <= err_1_fu_294_p2;
        err_2_reg_716 <= err_2_fu_300_p2;
        err_reg_702 <= err_fu_288_p2;
        kd_read_reg_687 <= kd;
        ki_read_reg_692 <= ki;
        kp_read_reg_697 <= kp;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln23_reg_805 <= icmp_ln23_fu_402_p2;
        sext_ln7_4_reg_795 <= sext_ln7_4_fu_396_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        icmp_ln28_1_reg_906 <= icmp_ln28_1_fu_572_p2;
        icmp_ln28_2_reg_916 <= icmp_ln28_2_fu_588_p2;
        icmp_ln28_reg_896 <= icmp_ln28_fu_556_p2;
        out_12_reg_901 <= out_12_fu_567_p2;
        out_9_reg_891 <= out_9_fu_551_p2;
        out_reg_911 <= out_fu_583_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_276 <= {{grp_fu_226_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_280 <= {{grp_fu_222_p2[47:16]}};
        reg_284 <= {{grp_fu_230_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        yaw_st_last_err <= err_2_reg_716;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_222_p0 = sext_ln7_10_fu_478_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_222_p0 = sext_ln7_3_fu_391_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_222_p0 = sext_ln7_fu_306_p1;
    end else begin
        grp_fu_222_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_222_p1 = sext_ln7_9_fu_472_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_222_p1 = sext_ln7_4_fu_396_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_222_p1 = sext_ln7_1_fu_312_p1;
    end else begin
        grp_fu_222_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_226_p0 = sext_ln7_11_fu_482_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_226_p0 = sext_ln7_6_fu_407_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_226_p0 = sext_ln7_2_fu_317_p1;
    end else begin
        grp_fu_226_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_226_p1 = sext_ln7_9_fu_472_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_226_p1 = sext_ln7_4_fu_396_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_226_p1 = sext_ln7_1_fu_312_p1;
    end else begin
        grp_fu_226_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_230_p0 = sext_ln7_12_fu_486_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_230_p0 = sext_ln7_8_fu_411_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_230_p0 = sext_ln7_fu_306_p1;
    end else begin
        grp_fu_230_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_230_p1 = sext_ln7_9_fu_472_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_230_p1 = sext_ln7_4_fu_396_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_230_p1 = sext_ln7_5_fu_337_p1;
    end else begin
        grp_fu_230_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_498_ap_start = 1'b1;
    end else begin
        grp_fu_498_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_511_ap_start = 1'b1;
    end else begin
        grp_fu_511_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_524_ap_start = 1'b1;
    end else begin
        grp_fu_524_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        out_pitch_ap_vld = 1'b1;
    end else begin
        out_pitch_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        out_roll_ap_vld = 1'b1;
    end else begin
        out_roll_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        out_yaw_ap_vld = 1'b1;
    end else begin
        out_yaw_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln23_reg_805 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_1_fu_444_p2 = (pitch_st_integ + reg_276);

assign add_ln20_2_fu_460_p2 = (yaw_st_integ + reg_284);

assign add_ln20_fu_428_p2 = (roll_st_integ + reg_280);

assign add_ln26_2_fu_562_p2 = (P_1_reg_770 + cond_i2773_reg_189);

assign add_ln26_4_fu_578_p2 = (P_2_reg_780 + D_reg_211);

assign add_ln26_fu_546_p2 = (P_reg_765 + cond_i6971_reg_200);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign diff_1_fu_346_p2 = ($signed(err_1_reg_709) - $signed(pitch_st_last_err));

assign diff_2_fu_419_p2 = ($signed(err_2_reg_716) - $signed(yaw_st_last_err));

assign diff_fu_327_p2 = ($signed(err_reg_702) - $signed(roll_st_last_err));

assign err_1_fu_294_p2 = (set_pitch - gyro_x);

assign err_2_fu_300_p2 = (set_yaw - gyro_z);

assign err_fu_288_p2 = (set_roll - gyro_y);

assign grp_fu_234_p0 = sext_ln7_2_fu_317_p1;

assign grp_fu_238_p1 = sext_ln7_7_fu_356_p1;

assign grp_fu_242_p0 = sext_ln7_2_fu_317_p1;

assign grp_fu_242_p1 = sext_ln7_7_fu_356_p1;

assign grp_fu_498_p0 = {{reg_280}, {16'd0}};

assign grp_fu_498_p1 = sext_ln7_4_reg_795;

assign grp_fu_511_p0 = {{reg_276}, {16'd0}};

assign grp_fu_511_p1 = sext_ln7_4_reg_795;

assign grp_fu_524_p0 = {{reg_284}, {16'd0}};

assign grp_fu_524_p1 = sext_ln7_4_reg_795;

assign icmp_ln23_fu_402_p2 = ((dt_read_reg_681 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_1_fu_572_p2 = (($signed(out_12_fu_567_p2) > $signed(32'd65536)) ? 1'b1 : 1'b0);

assign icmp_ln28_2_fu_588_p2 = (($signed(out_fu_583_p2) > $signed(32'd65536)) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_556_p2 = (($signed(out_9_fu_551_p2) > $signed(32'd65536)) ? 1'b1 : 1'b0);

assign icmp_ln29_1_fu_633_p2 = (($signed(out_13_fu_623_p3) < $signed(32'd4294901760)) ? 1'b1 : 1'b0);

assign icmp_ln29_2_fu_662_p2 = (($signed(out_7_fu_652_p3) < $signed(32'd4294901760)) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_604_p2 = (($signed(out_10_fu_594_p3) < $signed(32'd4294901760)) ? 1'b1 : 1'b0);

assign out_10_fu_594_p3 = ((icmp_ln28_reg_896[0:0] == 1'b1) ? 32'd65536 : out_9_reg_891);

assign out_11_fu_610_p3 = ((icmp_ln29_fu_604_p2[0:0] == 1'b1) ? 18'd196608 : trunc_ln29_fu_600_p1);

assign out_12_fu_567_p2 = (add_ln26_2_fu_562_p2 + add_ln20_1_reg_829);

assign out_13_fu_623_p3 = ((icmp_ln28_1_reg_906[0:0] == 1'b1) ? 32'd65536 : out_12_reg_901);

assign out_14_fu_639_p3 = ((icmp_ln29_1_fu_633_p2[0:0] == 1'b1) ? 18'd196608 : trunc_ln29_1_fu_629_p1);

assign out_7_fu_652_p3 = ((icmp_ln28_2_reg_916[0:0] == 1'b1) ? 32'd65536 : out_reg_911);

assign out_8_fu_668_p3 = ((icmp_ln29_2_fu_662_p2[0:0] == 1'b1) ? 18'd196608 : trunc_ln26_fu_658_p1);

assign out_9_fu_551_p2 = (add_ln26_fu_546_p2 + add_ln20_reg_824);

assign out_fu_583_p2 = (add_ln26_4_fu_578_p2 + add_ln20_2_reg_834);

assign out_pitch = $signed(out_14_fu_639_p3);

assign out_roll = $signed(out_11_fu_610_p3);

assign out_yaw = $signed(out_8_fu_668_p3);

assign sext_ln7_10_fu_478_p1 = $signed(diff_reg_743);

assign sext_ln7_11_fu_482_p1 = $signed(diff_1_reg_754);

assign sext_ln7_12_fu_486_p1 = $signed(diff_2_reg_819);

assign sext_ln7_1_fu_312_p1 = err_reg_702;

assign sext_ln7_2_fu_317_p1 = $signed(ki_read_reg_692);

assign sext_ln7_3_fu_391_p1 = $signed(reg_276);

assign sext_ln7_4_fu_396_p1 = dt_read_reg_681;

assign sext_ln7_5_fu_337_p1 = err_1_reg_709;

assign sext_ln7_6_fu_407_p1 = $signed(a_assign_1_reg_775);

assign sext_ln7_7_fu_356_p1 = err_2_reg_716;

assign sext_ln7_8_fu_411_p1 = $signed(a_assign_2_reg_785);

assign sext_ln7_9_fu_472_p1 = $signed(kd_read_reg_687);

assign sext_ln7_fu_306_p1 = kp_read_reg_697;

assign trunc_ln23_1_fu_533_p1 = grp_fu_511_p2[31:0];

assign trunc_ln23_2_fu_537_p1 = grp_fu_524_p2[31:0];

assign trunc_ln23_fu_529_p1 = grp_fu_498_p2[31:0];

assign trunc_ln26_fu_658_p1 = out_7_fu_652_p3[17:0];

assign trunc_ln29_1_fu_629_p1 = out_13_fu_623_p3[17:0];

assign trunc_ln29_fu_600_p1 = out_10_fu_594_p3[17:0];

endmodule //hardware_pid_engine
