-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hardware_pid_engine is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of hardware_pid_engine is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hardware_pid_engine_hardware_pid_engine,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.923000,HLS_SYN_LAT=34,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4485,HLS_SYN_LUT=3673,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (60 downto 0) := "0000000001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (60 downto 0) := "0000000010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (60 downto 0) := "0000000100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (60 downto 0) := "0000001000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (60 downto 0) := "0000010000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state57 : STD_LOGIC_VECTOR (60 downto 0) := "0000100000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state58 : STD_LOGIC_VECTOR (60 downto 0) := "0001000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state59 : STD_LOGIC_VECTOR (60 downto 0) := "0010000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state60 : STD_LOGIC_VECTOR (60 downto 0) := "0100000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state61 : STD_LOGIC_VECTOR (60 downto 0) := "1000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000010000000000000000";
    constant ap_const_lv32_FFFF0000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111110000000000000000";
    constant ap_const_lv18_30000 : STD_LOGIC_VECTOR (17 downto 0) := "110000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (60 downto 0) := "0000000000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal set_roll : STD_LOGIC_VECTOR (31 downto 0);
    signal set_pitch : STD_LOGIC_VECTOR (31 downto 0);
    signal set_yaw : STD_LOGIC_VECTOR (31 downto 0);
    signal gyro_x : STD_LOGIC_VECTOR (31 downto 0);
    signal gyro_y : STD_LOGIC_VECTOR (31 downto 0);
    signal gyro_z : STD_LOGIC_VECTOR (31 downto 0);
    signal kp : STD_LOGIC_VECTOR (31 downto 0);
    signal ki : STD_LOGIC_VECTOR (31 downto 0);
    signal kd : STD_LOGIC_VECTOR (31 downto 0);
    signal dt : STD_LOGIC_VECTOR (31 downto 0);
    signal throttle : STD_LOGIC_VECTOR (31 downto 0);
    signal out_roll : STD_LOGIC_VECTOR (31 downto 0);
    signal out_roll_ap_vld : STD_LOGIC;
    signal out_pitch : STD_LOGIC_VECTOR (31 downto 0);
    signal out_pitch_ap_vld : STD_LOGIC;
    signal out_yaw : STD_LOGIC_VECTOR (31 downto 0);
    signal out_yaw_ap_vld : STD_LOGIC;
    signal roll_st_integ : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal roll_st_last_err : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pitch_st_integ : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pitch_st_last_err : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal yaw_st_integ : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal yaw_st_last_err : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal reg_276 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal reg_280 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_284 : STD_LOGIC_VECTOR (31 downto 0);
    signal dt_read_reg_681 : STD_LOGIC_VECTOR (31 downto 0);
    signal kd_read_reg_687 : STD_LOGIC_VECTOR (31 downto 0);
    signal ki_read_reg_692 : STD_LOGIC_VECTOR (31 downto 0);
    signal kp_read_reg_697 : STD_LOGIC_VECTOR (31 downto 0);
    signal err_fu_288_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal err_reg_702 : STD_LOGIC_VECTOR (31 downto 0);
    signal err_1_fu_294_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal err_1_reg_709 : STD_LOGIC_VECTOR (31 downto 0);
    signal err_2_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal err_2_reg_716 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln7_fu_306_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln7_1_fu_312_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln7_2_fu_317_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal diff_fu_327_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_reg_743 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln7_5_fu_337_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal diff_1_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_1_reg_754 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln7_7_fu_356_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal P_reg_765 : STD_LOGIC_VECTOR (31 downto 0);
    signal P_1_reg_770 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_assign_1_reg_775 : STD_LOGIC_VECTOR (31 downto 0);
    signal P_2_reg_780 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_assign_2_reg_785 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln7_3_fu_391_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sext_ln7_4_fu_396_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln7_4_reg_795 : STD_LOGIC_VECTOR (47 downto 0);
    signal icmp_ln23_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_reg_805 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln7_6_fu_407_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln7_8_fu_411_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal diff_2_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_2_reg_819 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln20_fu_428_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln20_reg_824 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln20_1_fu_444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln20_1_reg_829 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln20_2_fu_460_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln20_2_reg_834 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln7_9_fu_472_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln7_10_fu_478_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln7_11_fu_482_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln7_12_fu_486_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal trunc_ln23_fu_529_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state59 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state59 : signal is "none";
    signal trunc_ln23_1_fu_533_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln23_2_fu_537_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_9_fu_551_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_9_reg_891 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state60 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state60 : signal is "none";
    signal icmp_ln28_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_reg_896 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_12_fu_567_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_12_reg_901 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln28_1_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_1_reg_906 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_fu_583_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_reg_911 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln28_2_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_2_reg_916 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_i2773_reg_189 : STD_LOGIC_VECTOR (31 downto 0);
    signal cond_i6971_reg_200 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_reg_211 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state61 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state61 : signal is "none";
    signal grp_fu_222_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_226_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_226_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_230_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_230_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_234_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_238_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_242_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_242_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_222_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_226_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_230_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_234_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_238_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_242_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_498_p0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_498_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_511_p0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_511_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_524_p0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_524_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_498_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_511_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_524_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln26_fu_546_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln26_2_fu_562_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln26_4_fu_578_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_10_fu_594_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln29_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_fu_600_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_11_fu_610_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_13_fu_623_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln29_1_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_1_fu_629_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_14_fu_639_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_7_fu_652_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln29_2_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln26_fu_658_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_8_fu_668_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_498_ap_start : STD_LOGIC;
    signal grp_fu_498_ap_done : STD_LOGIC;
    signal grp_fu_511_ap_start : STD_LOGIC;
    signal grp_fu_511_ap_done : STD_LOGIC;
    signal grp_fu_524_ap_start : STD_LOGIC;
    signal grp_fu_524_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (60 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal ap_ST_fsm_state40_blk : STD_LOGIC;
    signal ap_ST_fsm_state41_blk : STD_LOGIC;
    signal ap_ST_fsm_state42_blk : STD_LOGIC;
    signal ap_ST_fsm_state43_blk : STD_LOGIC;
    signal ap_ST_fsm_state44_blk : STD_LOGIC;
    signal ap_ST_fsm_state45_blk : STD_LOGIC;
    signal ap_ST_fsm_state46_blk : STD_LOGIC;
    signal ap_ST_fsm_state47_blk : STD_LOGIC;
    signal ap_ST_fsm_state48_blk : STD_LOGIC;
    signal ap_ST_fsm_state49_blk : STD_LOGIC;
    signal ap_ST_fsm_state50_blk : STD_LOGIC;
    signal ap_ST_fsm_state51_blk : STD_LOGIC;
    signal ap_ST_fsm_state52_blk : STD_LOGIC;
    signal ap_ST_fsm_state53_blk : STD_LOGIC;
    signal ap_ST_fsm_state54_blk : STD_LOGIC;
    signal ap_ST_fsm_state55_blk : STD_LOGIC;
    signal ap_ST_fsm_state56_blk : STD_LOGIC;
    signal ap_ST_fsm_state57_blk : STD_LOGIC;
    signal ap_ST_fsm_state58_blk : STD_LOGIC;
    signal ap_ST_fsm_state59_blk : STD_LOGIC;
    signal ap_ST_fsm_state60_blk : STD_LOGIC;
    signal ap_ST_fsm_state61_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hardware_pid_engine_mul_32s_32s_48_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (47 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hardware_pid_engine_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        set_roll : OUT STD_LOGIC_VECTOR (31 downto 0);
        set_pitch : OUT STD_LOGIC_VECTOR (31 downto 0);
        set_yaw : OUT STD_LOGIC_VECTOR (31 downto 0);
        gyro_x : OUT STD_LOGIC_VECTOR (31 downto 0);
        gyro_y : OUT STD_LOGIC_VECTOR (31 downto 0);
        gyro_z : OUT STD_LOGIC_VECTOR (31 downto 0);
        kp : OUT STD_LOGIC_VECTOR (31 downto 0);
        ki : OUT STD_LOGIC_VECTOR (31 downto 0);
        kd : OUT STD_LOGIC_VECTOR (31 downto 0);
        dt : OUT STD_LOGIC_VECTOR (31 downto 0);
        throttle : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_roll : IN STD_LOGIC_VECTOR (31 downto 0);
        out_roll_ap_vld : IN STD_LOGIC;
        out_pitch : IN STD_LOGIC_VECTOR (31 downto 0);
        out_pitch_ap_vld : IN STD_LOGIC;
        out_yaw : IN STD_LOGIC_VECTOR (31 downto 0);
        out_yaw_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    CTRL_BUS_s_axi_U : component hardware_pid_engine_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        set_roll => set_roll,
        set_pitch => set_pitch,
        set_yaw => set_yaw,
        gyro_x => gyro_x,
        gyro_y => gyro_y,
        gyro_z => gyro_z,
        kp => kp,
        ki => ki,
        kd => kd,
        dt => dt,
        throttle => throttle,
        out_roll => out_roll,
        out_roll_ap_vld => out_roll_ap_vld,
        out_pitch => out_pitch,
        out_pitch_ap_vld => out_pitch_ap_vld,
        out_yaw => out_yaw,
        out_yaw_ap_vld => out_yaw_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32s_32s_48_2_1_U1 : component hardware_pid_engine_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_222_p0,
        din1 => grp_fu_222_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_222_p2);

    mul_32s_32s_48_2_1_U2 : component hardware_pid_engine_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_226_p0,
        din1 => grp_fu_226_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_226_p2);

    mul_32s_32s_48_2_1_U3 : component hardware_pid_engine_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_230_p0,
        din1 => grp_fu_230_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_230_p2);

    mul_32s_32s_48_2_1_U4 : component hardware_pid_engine_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_234_p0,
        din1 => err_1_reg_709,
        ce => ap_const_logic_1,
        dout => grp_fu_234_p2);

    mul_32s_32s_48_2_1_U5 : component hardware_pid_engine_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => kp_read_reg_697,
        din1 => grp_fu_238_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_238_p2);

    mul_32s_32s_48_2_1_U6 : component hardware_pid_engine_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_242_p0,
        din1 => grp_fu_242_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_242_p2);

    sdiv_48ns_32s_32_52_seq_1_U7 : component hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 52,
        din0_WIDTH => 48,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_498_ap_start,
        done => grp_fu_498_ap_done,
        din0 => grp_fu_498_p0,
        din1 => grp_fu_498_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_498_p2);

    sdiv_48ns_32s_32_52_seq_1_U8 : component hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 52,
        din0_WIDTH => 48,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_511_ap_start,
        done => grp_fu_511_ap_done,
        din0 => grp_fu_511_p0,
        din1 => grp_fu_511_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_511_p2);

    sdiv_48ns_32s_32_52_seq_1_U9 : component hardware_pid_engine_sdiv_48ns_32s_32_52_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 52,
        din0_WIDTH => 48,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_524_ap_start,
        done => grp_fu_524_ap_done,
        din0 => grp_fu_524_p0,
        din1 => grp_fu_524_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_524_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    D_reg_211_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln23_reg_805 = ap_const_lv1_1))) then 
                D_reg_211 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state59) and (icmp_ln23_reg_805 = ap_const_lv1_0))) then 
                D_reg_211 <= trunc_ln23_2_fu_537_p1;
            end if; 
        end if;
    end process;

    cond_i2773_reg_189_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln23_reg_805 = ap_const_lv1_1))) then 
                cond_i2773_reg_189 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state59) and (icmp_ln23_reg_805 = ap_const_lv1_0))) then 
                cond_i2773_reg_189 <= trunc_ln23_1_fu_533_p1;
            end if; 
        end if;
    end process;

    cond_i6971_reg_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln23_reg_805 = ap_const_lv1_1))) then 
                cond_i6971_reg_200 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state59) and (icmp_ln23_reg_805 = ap_const_lv1_0))) then 
                cond_i6971_reg_200 <= trunc_ln23_fu_529_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                P_1_reg_770 <= grp_fu_230_p2(47 downto 16);
                P_2_reg_780 <= grp_fu_238_p2(47 downto 16);
                P_reg_765 <= grp_fu_222_p2(47 downto 16);
                a_assign_1_reg_775 <= grp_fu_234_p2(47 downto 16);
                a_assign_2_reg_785 <= grp_fu_242_p2(47 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln20_1_reg_829 <= add_ln20_1_fu_444_p2;
                add_ln20_2_reg_834 <= add_ln20_2_fu_460_p2;
                add_ln20_reg_824 <= add_ln20_fu_428_p2;
                pitch_st_integ <= add_ln20_1_fu_444_p2;
                roll_st_integ <= add_ln20_fu_428_p2;
                yaw_st_integ <= add_ln20_2_fu_460_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                diff_1_reg_754 <= diff_1_fu_346_p2;
                diff_reg_743 <= diff_fu_327_p2;
                pitch_st_last_err <= err_1_reg_709;
                roll_st_last_err <= err_reg_702;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                diff_2_reg_819 <= diff_2_fu_419_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                dt_read_reg_681 <= dt;
                err_1_reg_709 <= err_1_fu_294_p2;
                err_2_reg_716 <= err_2_fu_300_p2;
                err_reg_702 <= err_fu_288_p2;
                kd_read_reg_687 <= kd;
                ki_read_reg_692 <= ki;
                kp_read_reg_697 <= kp;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln23_reg_805 <= icmp_ln23_fu_402_p2;
                sext_ln7_4_reg_795 <= sext_ln7_4_fu_396_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state60)) then
                icmp_ln28_1_reg_906 <= icmp_ln28_1_fu_572_p2;
                icmp_ln28_2_reg_916 <= icmp_ln28_2_fu_588_p2;
                icmp_ln28_reg_896 <= icmp_ln28_fu_556_p2;
                out_12_reg_901 <= out_12_fu_567_p2;
                out_9_reg_891 <= out_9_fu_551_p2;
                out_reg_911 <= out_fu_583_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_276 <= grp_fu_226_p2(47 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_280 <= grp_fu_222_p2(47 downto 16);
                reg_284 <= grp_fu_230_p2(47 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state59)) then
                yaw_st_last_err <= err_2_reg_716;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln23_reg_805, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln23_reg_805 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state59;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state51 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state53;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state57;
            when ap_ST_fsm_state57 => 
                ap_NS_fsm <= ap_ST_fsm_state58;
            when ap_ST_fsm_state58 => 
                ap_NS_fsm <= ap_ST_fsm_state59;
            when ap_ST_fsm_state59 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state60 => 
                ap_NS_fsm <= ap_ST_fsm_state61;
            when ap_ST_fsm_state61 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln20_1_fu_444_p2 <= std_logic_vector(unsigned(pitch_st_integ) + unsigned(reg_276));
    add_ln20_2_fu_460_p2 <= std_logic_vector(unsigned(yaw_st_integ) + unsigned(reg_284));
    add_ln20_fu_428_p2 <= std_logic_vector(unsigned(roll_st_integ) + unsigned(reg_280));
    add_ln26_2_fu_562_p2 <= std_logic_vector(unsigned(P_1_reg_770) + unsigned(cond_i2773_reg_189));
    add_ln26_4_fu_578_p2 <= std_logic_vector(unsigned(P_2_reg_780) + unsigned(D_reg_211));
    add_ln26_fu_546_p2 <= std_logic_vector(unsigned(P_reg_765) + unsigned(cond_i6971_reg_200));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state59 <= ap_CS_fsm(58);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state60 <= ap_CS_fsm(59);
    ap_CS_fsm_state61 <= ap_CS_fsm(60);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state39_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state40_blk <= ap_const_logic_0;
    ap_ST_fsm_state41_blk <= ap_const_logic_0;
    ap_ST_fsm_state42_blk <= ap_const_logic_0;
    ap_ST_fsm_state43_blk <= ap_const_logic_0;
    ap_ST_fsm_state44_blk <= ap_const_logic_0;
    ap_ST_fsm_state45_blk <= ap_const_logic_0;
    ap_ST_fsm_state46_blk <= ap_const_logic_0;
    ap_ST_fsm_state47_blk <= ap_const_logic_0;
    ap_ST_fsm_state48_blk <= ap_const_logic_0;
    ap_ST_fsm_state49_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state50_blk <= ap_const_logic_0;
    ap_ST_fsm_state51_blk <= ap_const_logic_0;
    ap_ST_fsm_state52_blk <= ap_const_logic_0;
    ap_ST_fsm_state53_blk <= ap_const_logic_0;
    ap_ST_fsm_state54_blk <= ap_const_logic_0;
    ap_ST_fsm_state55_blk <= ap_const_logic_0;
    ap_ST_fsm_state56_blk <= ap_const_logic_0;
    ap_ST_fsm_state57_blk <= ap_const_logic_0;
    ap_ST_fsm_state58_blk <= ap_const_logic_0;
    ap_ST_fsm_state59_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state60_blk <= ap_const_logic_0;
    ap_ST_fsm_state61_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state61)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state61)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state61)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state61)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    diff_1_fu_346_p2 <= std_logic_vector(signed(err_1_reg_709) - signed(pitch_st_last_err));
    diff_2_fu_419_p2 <= std_logic_vector(signed(err_2_reg_716) - signed(yaw_st_last_err));
    diff_fu_327_p2 <= std_logic_vector(signed(err_reg_702) - signed(roll_st_last_err));
    err_1_fu_294_p2 <= std_logic_vector(unsigned(set_pitch) - unsigned(gyro_x));
    err_2_fu_300_p2 <= std_logic_vector(unsigned(set_yaw) - unsigned(gyro_z));
    err_fu_288_p2 <= std_logic_vector(unsigned(set_roll) - unsigned(gyro_y));

    grp_fu_222_p0_assign_proc : process(sext_ln7_fu_306_p1, ap_CS_fsm_state2, sext_ln7_3_fu_391_p1, ap_CS_fsm_state4, ap_CS_fsm_state6, sext_ln7_10_fu_478_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_222_p0 <= sext_ln7_10_fu_478_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_222_p0 <= sext_ln7_3_fu_391_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_222_p0 <= sext_ln7_fu_306_p1(32 - 1 downto 0);
        else 
            grp_fu_222_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_222_p1_assign_proc : process(ap_CS_fsm_state2, sext_ln7_1_fu_312_p1, ap_CS_fsm_state4, sext_ln7_4_fu_396_p1, ap_CS_fsm_state6, sext_ln7_9_fu_472_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_222_p1 <= sext_ln7_9_fu_472_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_222_p1 <= sext_ln7_4_fu_396_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_222_p1 <= sext_ln7_1_fu_312_p1(32 - 1 downto 0);
        else 
            grp_fu_222_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_226_p0_assign_proc : process(ap_CS_fsm_state2, sext_ln7_2_fu_317_p1, ap_CS_fsm_state4, sext_ln7_6_fu_407_p1, ap_CS_fsm_state6, sext_ln7_11_fu_482_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_226_p0 <= sext_ln7_11_fu_482_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_226_p0 <= sext_ln7_6_fu_407_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_226_p0 <= sext_ln7_2_fu_317_p1(32 - 1 downto 0);
        else 
            grp_fu_226_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_226_p1_assign_proc : process(ap_CS_fsm_state2, sext_ln7_1_fu_312_p1, ap_CS_fsm_state4, sext_ln7_4_fu_396_p1, ap_CS_fsm_state6, sext_ln7_9_fu_472_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_226_p1 <= sext_ln7_9_fu_472_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_226_p1 <= sext_ln7_4_fu_396_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_226_p1 <= sext_ln7_1_fu_312_p1(32 - 1 downto 0);
        else 
            grp_fu_226_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_230_p0_assign_proc : process(sext_ln7_fu_306_p1, ap_CS_fsm_state2, ap_CS_fsm_state4, sext_ln7_8_fu_411_p1, ap_CS_fsm_state6, sext_ln7_12_fu_486_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_230_p0 <= sext_ln7_12_fu_486_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_230_p0 <= sext_ln7_8_fu_411_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_230_p0 <= sext_ln7_fu_306_p1(32 - 1 downto 0);
        else 
            grp_fu_230_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_230_p1_assign_proc : process(ap_CS_fsm_state2, sext_ln7_5_fu_337_p1, ap_CS_fsm_state4, sext_ln7_4_fu_396_p1, ap_CS_fsm_state6, sext_ln7_9_fu_472_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_230_p1 <= sext_ln7_9_fu_472_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_230_p1 <= sext_ln7_4_fu_396_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_230_p1 <= sext_ln7_5_fu_337_p1(32 - 1 downto 0);
        else 
            grp_fu_230_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_234_p0 <= sext_ln7_2_fu_317_p1(32 - 1 downto 0);
    grp_fu_238_p1 <= sext_ln7_7_fu_356_p1(32 - 1 downto 0);
    grp_fu_242_p0 <= sext_ln7_2_fu_317_p1(32 - 1 downto 0);
    grp_fu_242_p1 <= sext_ln7_7_fu_356_p1(32 - 1 downto 0);

    grp_fu_498_ap_start_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_498_ap_start <= ap_const_logic_1;
        else 
            grp_fu_498_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_498_p0 <= (reg_280 & ap_const_lv16_0);
    grp_fu_498_p1 <= sext_ln7_4_reg_795(32 - 1 downto 0);

    grp_fu_511_ap_start_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_511_ap_start <= ap_const_logic_1;
        else 
            grp_fu_511_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_511_p0 <= (reg_276 & ap_const_lv16_0);
    grp_fu_511_p1 <= sext_ln7_4_reg_795(32 - 1 downto 0);

    grp_fu_524_ap_start_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_524_ap_start <= ap_const_logic_1;
        else 
            grp_fu_524_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_524_p0 <= (reg_284 & ap_const_lv16_0);
    grp_fu_524_p1 <= sext_ln7_4_reg_795(32 - 1 downto 0);
    icmp_ln23_fu_402_p2 <= "1" when (dt_read_reg_681 = ap_const_lv32_0) else "0";
    icmp_ln28_1_fu_572_p2 <= "1" when (signed(out_12_fu_567_p2) > signed(ap_const_lv32_10000)) else "0";
    icmp_ln28_2_fu_588_p2 <= "1" when (signed(out_fu_583_p2) > signed(ap_const_lv32_10000)) else "0";
    icmp_ln28_fu_556_p2 <= "1" when (signed(out_9_fu_551_p2) > signed(ap_const_lv32_10000)) else "0";
    icmp_ln29_1_fu_633_p2 <= "1" when (signed(out_13_fu_623_p3) < signed(ap_const_lv32_FFFF0000)) else "0";
    icmp_ln29_2_fu_662_p2 <= "1" when (signed(out_7_fu_652_p3) < signed(ap_const_lv32_FFFF0000)) else "0";
    icmp_ln29_fu_604_p2 <= "1" when (signed(out_10_fu_594_p3) < signed(ap_const_lv32_FFFF0000)) else "0";
    out_10_fu_594_p3 <= 
        ap_const_lv32_10000 when (icmp_ln28_reg_896(0) = '1') else 
        out_9_reg_891;
    out_11_fu_610_p3 <= 
        ap_const_lv18_30000 when (icmp_ln29_fu_604_p2(0) = '1') else 
        trunc_ln29_fu_600_p1;
    out_12_fu_567_p2 <= std_logic_vector(unsigned(add_ln26_2_fu_562_p2) + unsigned(add_ln20_1_reg_829));
    out_13_fu_623_p3 <= 
        ap_const_lv32_10000 when (icmp_ln28_1_reg_906(0) = '1') else 
        out_12_reg_901;
    out_14_fu_639_p3 <= 
        ap_const_lv18_30000 when (icmp_ln29_1_fu_633_p2(0) = '1') else 
        trunc_ln29_1_fu_629_p1;
    out_7_fu_652_p3 <= 
        ap_const_lv32_10000 when (icmp_ln28_2_reg_916(0) = '1') else 
        out_reg_911;
    out_8_fu_668_p3 <= 
        ap_const_lv18_30000 when (icmp_ln29_2_fu_662_p2(0) = '1') else 
        trunc_ln26_fu_658_p1;
    out_9_fu_551_p2 <= std_logic_vector(unsigned(add_ln26_fu_546_p2) + unsigned(add_ln20_reg_824));
    out_fu_583_p2 <= std_logic_vector(unsigned(add_ln26_4_fu_578_p2) + unsigned(add_ln20_2_reg_834));
        out_pitch <= std_logic_vector(IEEE.numeric_std.resize(signed(out_14_fu_639_p3),32));


    out_pitch_ap_vld_assign_proc : process(ap_CS_fsm_state61)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state61)) then 
            out_pitch_ap_vld <= ap_const_logic_1;
        else 
            out_pitch_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        out_roll <= std_logic_vector(IEEE.numeric_std.resize(signed(out_11_fu_610_p3),32));


    out_roll_ap_vld_assign_proc : process(ap_CS_fsm_state61)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state61)) then 
            out_roll_ap_vld <= ap_const_logic_1;
        else 
            out_roll_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        out_yaw <= std_logic_vector(IEEE.numeric_std.resize(signed(out_8_fu_668_p3),32));


    out_yaw_ap_vld_assign_proc : process(ap_CS_fsm_state61)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state61)) then 
            out_yaw_ap_vld <= ap_const_logic_1;
        else 
            out_yaw_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln7_10_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(diff_reg_743),48));

        sext_ln7_11_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(diff_1_reg_754),48));

        sext_ln7_12_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(diff_2_reg_819),48));

        sext_ln7_1_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(err_reg_702),48));

        sext_ln7_2_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ki_read_reg_692),48));

        sext_ln7_3_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_276),48));

        sext_ln7_4_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(dt_read_reg_681),48));

        sext_ln7_5_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(err_1_reg_709),48));

        sext_ln7_6_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_assign_1_reg_775),48));

        sext_ln7_7_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(err_2_reg_716),48));

        sext_ln7_8_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_assign_2_reg_785),48));

        sext_ln7_9_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(kd_read_reg_687),48));

        sext_ln7_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(kp_read_reg_697),48));

    trunc_ln23_1_fu_533_p1 <= grp_fu_511_p2(32 - 1 downto 0);
    trunc_ln23_2_fu_537_p1 <= grp_fu_524_p2(32 - 1 downto 0);
    trunc_ln23_fu_529_p1 <= grp_fu_498_p2(32 - 1 downto 0);
    trunc_ln26_fu_658_p1 <= out_7_fu_652_p3(18 - 1 downto 0);
    trunc_ln29_1_fu_629_p1 <= out_13_fu_623_p3(18 - 1 downto 0);
    trunc_ln29_fu_600_p1 <= out_10_fu_594_p3(18 - 1 downto 0);
end behav;
