

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
		"CDFG" : "hardware_pid_engine",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "8", "EstimateLatencyMax" : "60",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "set_roll", "Type" : "None", "Direction" : "I"},
			{"Name" : "set_pitch", "Type" : "None", "Direction" : "I"},
			{"Name" : "set_yaw", "Type" : "None", "Direction" : "I"},
			{"Name" : "gyro_x", "Type" : "None", "Direction" : "I"},
			{"Name" : "gyro_y", "Type" : "None", "Direction" : "I"},
			{"Name" : "gyro_z", "Type" : "None", "Direction" : "I"},
			{"Name" : "kp", "Type" : "None", "Direction" : "I"},
			{"Name" : "ki", "Type" : "None", "Direction" : "I"},
			{"Name" : "kd", "Type" : "None", "Direction" : "I"},
			{"Name" : "dt", "Type" : "None", "Direction" : "I"},
			{"Name" : "throttle", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_roll", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "out_pitch", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "out_yaw", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "roll_st_integ", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "roll_st_last_err", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "pitch_st_integ", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "pitch_st_last_err", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "yaw_st_integ", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "yaw_st_last_err", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_BUS_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_48_2_1_U1", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_48_2_1_U2", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_48_2_1_U3", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_48_2_1_U4", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_48_2_1_U5", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_48_2_1_U6", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sdiv_48ns_32s_32_52_seq_1_U7", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sdiv_48ns_32s_32_52_seq_1_U8", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sdiv_48ns_32s_32_52_seq_1_U9", "Parent" : "0"}]}
