# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mpu6050_constraints.xdc

# Block Designs: bd/drone_block_design/drone_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design || ORIG_REF_NAME==drone_block_design} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_processing_system7_0_0/drone_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_processing_system7_0_0 || ORIG_REF_NAME==drone_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_axi_dma_0_0/drone_block_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_axi_dma_0_0 || ORIG_REF_NAME==drone_block_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_mpu6050_axis_ip_0_0/drone_block_design_mpu6050_axis_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_mpu6050_axis_ip_0_0 || ORIG_REF_NAME==drone_block_design_mpu6050_axis_ip_0_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_axi_smc_1/drone_block_design_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_axi_smc_1 || ORIG_REF_NAME==drone_block_design_axi_smc_1} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_rst_ps7_0_100M_1/drone_block_design_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_rst_ps7_0_100M_1 || ORIG_REF_NAME==drone_block_design_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_0/drone_block_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_axi_mem_intercon_0 || ORIG_REF_NAME==drone_block_design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_util_ds_buf_0_0/drone_block_design_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_util_ds_buf_0_0 || ORIG_REF_NAME==drone_block_design_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_util_ds_buf_1_0/drone_block_design_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_util_ds_buf_1_0 || ORIG_REF_NAME==drone_block_design_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_xlconstant_0_0/drone_block_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_xlconstant_0_0 || ORIG_REF_NAME==drone_block_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_xlconstant_1_0/drone_block_design_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_xlconstant_1_0 || ORIG_REF_NAME==drone_block_design_xlconstant_1_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_imp_auto_ds_0/drone_block_design_axi_mem_intercon_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_axi_mem_intercon_imp_auto_ds_0 || ORIG_REF_NAME==drone_block_design_axi_mem_intercon_imp_auto_ds_0} -quiet] -quiet

# IP: bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_imp_auto_pc_0/drone_block_design_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==drone_block_design_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==drone_block_design_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/drone_block_design_ooc.xdc
