# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.runs/synth_1/drone_block_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param bd.open.in_stealth_mode 2
set_msg_config  -id {IP_Flow 19-5905}  -string {{WARNING: [IP_Flow 19-5905] All packaged files should be located below the IP definition file (xml)}}  -suppress 
set_msg_config  -id {IP_Flow 19-625}  -string {{CRITICAL WARNING: [IP_Flow 19-625] File Group 'xilinx_verilogsynthesis (Verilog Synthesis)': One or more vhdlSource files found added to the pure language Verilog file group: ../mpu6050_axis.vhd,...}}  -suppress 
set_msg_config  -id {IP_Flow 19-2187}  -string {{WARNING: [IP_Flow 19-2187] The Product Guide file is missing.}}  -suppress 
set_msg_config  -id {IP_Flow 19-5661}  -string {{WARNING: [IP_Flow 19-5661] Bus Interface 'clk' does not have any bus interfaces associated with it.}}  -suppress 
set_msg_config  -id {IP_Flow 19-11770}  -string {{WARNING: [IP_Flow 19-11770] Clock interface 'clk' has no FREQ_HZ parameter.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.cache/wt [current_project]
set_property parent.project_path C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/lomin/AppData/Roaming/Xilinx/Vivado/2025.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/lomin/Documents/git/DRONE/rtl_controller/ip_repo/mpu6050_axis_ip_1_0
  c:/Users/lomin/Documents/git/DRONE/rtl_controller/ip_repo/mpu6050_axis_ip_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/hdl/drone_block_design_wrapper.vhd
add_files C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.srcs/sources_1/bd/drone_block_design/drone_block_design.bd
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_processing_system7_0_0/drone_block_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_dma_0_0/drone_block_design_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_dma_0_0/drone_block_design_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_dma_0_0/drone_block_design_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_1/bd_6acc_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_5/bd_6acc_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_6/bd_6acc_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_7/bd_6acc_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_8/bd_6acc_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_9/bd_6acc_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_10/bd_6acc_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/bd_0/ip/ip_11/bd_6acc_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_smc_1/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_rst_ps7_0_100M_1/drone_block_design_rst_ps7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_rst_ps7_0_100M_1/drone_block_design_rst_ps7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_util_ds_buf_0_0/drone_block_design_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_util_ds_buf_0_0/drone_block_design_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_util_ds_buf_1_0/drone_block_design_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_util_ds_buf_1_0/drone_block_design_util_ds_buf_1_0_board.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_imp_auto_ds_0/drone_block_design_axi_mem_intercon_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_imp_auto_ds_0/drone_block_design_axi_mem_intercon_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_imp_auto_ds_0/drone_block_design_axi_mem_intercon_imp_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/ip/drone_block_design_axi_mem_intercon_imp_auto_pc_0/drone_block_design_axi_mem_intercon_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.gen/sources_1/bd/drone_block_design/drone_block_design_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.srcs/constrs_1/new/mpu6050_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.srcs/constrs_1/new/mpu6050_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/lomin/Documents/git/DRONE/rtl_controller/drone_overlay/drone_overlay.srcs/utils_1/imports/synth_1/drone_block_design_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top drone_block_design_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef drone_block_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file drone_block_design_wrapper_utilization_synth.rpt -pb drone_block_design_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
